# Generated by Django 4.2.30 on 2026-09-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("farmer", "Farmer"),
                    ("expert", "Agronomist / Expert"),
                    ("officer", "Agricultural Officer"),
                ],
                default="farmer",
                max_length=20,
            ),
        ),
    ]
