# Generated by Django 4.2.30 on 2026-09-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assigned_region",
            field=models.CharField(
                blank=True,
                default="",
                help_text='State/district/taluka string for region scoping, e.g. "Gujarat / Anand"',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="assigned_region_lat",
            field=models.FloatField(
                blank=True,
                help_text="Center latitude of assigned region (for distance-based scoping)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="assigned_region_lon",
            field=models.FloatField(
                blank=True,
                help_text="Center longitude of assigned region (for distance-based scoping)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="assigned_region_radius_km",
            field=models.FloatField(
                blank=True,
                default=50.0,
                help_text="Radius in km around assigned lat/lon",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="credentials_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text='e.g. "KVK Ahmedabad, registered agronomist"',
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified_expert",
            field=models.BooleanField(
                default=False,
                help_text="Set by officer/admin to mark this expert as credential-verified",
            ),
        ),
    ]
