# Generated by Django 4.2.30 on 2026-09-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_assigned_region_user_assigned_region_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_demo",
            field=models.BooleanField(
                default=False,
                help_text="True if this account is a demonstration profile",
            ),
        ),
    ]
