# Generated by Django 4.2.30 on 2026-09-12 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0004_remove_crop_area_acres_remove_crop_irrigation_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmartIrrigationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop", models.CharField(max_length=100)),
                ("soil_type", models.CharField(max_length=100)),
                ("growth_stage", models.CharField(max_length=150)),
                (
                    "soil_moisture",
                    models.FloatField(help_text="Soil moisture percentage 0-100%"),
                ),
                (
                    "temperature",
                    models.FloatField(help_text="Ambient temperature in Celsius"),
                ),
                (
                    "humidity",
                    models.FloatField(help_text="Relative humidity percentage 0-100%"),
                ),
                ("rain_probability", models.FloatField(default=0.0)),
                ("forecast_rainfall_mm", models.FloatField(default=0.0)),
                (
                    "predicted_class",
                    models.IntegerField(help_text="0: No, 1: Yes, 2: Excess"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("no_irrigation", "No Irrigation Required"),
                            ("irrigation_required", "Irrigation Required"),
                            ("excess_water", "Excess Water Detected"),
                        ],
                        max_length=50,
                    ),
                ),
                ("action", models.CharField(max_length=50)),
                ("urgency", models.CharField(default="low", max_length=20)),
                (
                    "confidence",
                    models.FloatField(help_text="Confidence score 0.0 - 1.0"),
                ),
                ("recommendation", models.TextField()),
                ("explanation", models.TextField(blank=True)),
                ("weather_modified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smart_irrigation_records",
                        to="farms.farm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_irrigation_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
