# Generated by Django 4.2.30 on 2026-09-23 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0005_farm_crop_stage"),
        ("disease", "0002_diseasescan_disease_name_diseasescan_plant_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(default="Unknown", max_length=100)),
                ("crop_stage", models.CharField(default="vegetative", max_length=50)),
                (
                    "risk_score",
                    models.FloatField(
                        default=0.0, help_text="Computed risk score from 0 to 100"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                (
                    "breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="Component scores (disease_confidence, severity, humidity, temp, rain, crop_stage, pest, local_incidence)",
                    ),
                ),
                (
                    "ipm_actions",
                    models.JSONField(
                        default=dict,
                        help_text="Tiered IPM recommendations (cultural, biological, chemical guidance)",
                    ),
                ),
                (
                    "forecast",
                    models.JSONField(
                        default=list, help_text="7-day risk progression forecast"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_assessments",
                        to="farms.farm",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_assessments",
                        to="disease.diseasescan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
