# Generated by Django 4.2.30 on 2026-09-11 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiseaseScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="disease_scans/%Y/%m/"
                    ),
                ),
                ("predicted_class", models.CharField(blank=True, max_length=200)),
                (
                    "confidence",
                    models.FloatField(blank=True, help_text="0.0 – 1.0", null=True),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None / Healthy"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_healthy", models.BooleanField(blank=True, null=True)),
                (
                    "model_status",
                    models.CharField(
                        choices=[
                            ("pending", "Model Pending"),
                            ("ready", "Analyzed"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("crop_type", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disease_scans",
                        to="farms.farm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disease_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
