# Generated by Django 4.2.30 on 2026-09-15 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasescan',
            name='disease_name',
            field=models.CharField(blank=True, default='', help_text='Detected disease name', max_length=200),
        ),
        migrations.AddField(
            model_name='diseasescan',
            name='plant_name',
            field=models.CharField(blank=True, default='', help_text='Detected crop/plant name', max_length=100),
        ),
    ]
