# Generated by Django 4.2.30 on 2026-09-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disease", "0002_diseasescan_disease_name_diseasescan_plant_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="diseasescan",
            name="needs_expert_review",
            field=models.BooleanField(
                default=False,
                help_text="Auto-set when risk is high/critical or confidence is low",
            ),
        ),
        migrations.AddField(
            model_name="diseasescan",
            name="priority",
            field=models.CharField(
                choices=[("normal", "Normal"), ("urgent", "Urgent")],
                default="normal",
                help_text="Urgency level for expert queue sorting",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="diseasescan",
            name="referral_recommended",
            field=models.BooleanField(
                default=False,
                help_text="True if risk is critical or confidence is too low for reliable diagnosis",
            ),
        ),
    ]
