# Generated by Django 4.2.30 on 2026-09-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "disease",
            "0003_diseasescan_needs_expert_review_diseasescan_priority_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="diseasescan",
            name="farmer_leaf_extent",
            field=models.CharField(blank=True, default="unknown", max_length=20),
        ),
        migrations.AlterField(
            model_name="diseasescan",
            name="confidence",
            field=models.FloatField(
                blank=True, help_text="0.0 – 1.0 (uncalibrated softmax)", null=True
            ),
        ),
    ]
