# Generated by Django 4.2.30 on 2026-09-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("expert_review_needed", "Expert Review Needed"),
                    ("expert_review_completed", "Expert Review Completed"),
                    ("hotspot_dispatch", "Hotspot Advisory Dispatch"),
                    ("followup_due", "Follow-up Due"),
                    ("referral_recommended", "Referral Recommended"),
                    ("high_risk_forecast", "High Risk Forecast Alert"),
                    ("pest_threshold_exceeded", "Pest Threshold Exceeded"),
                ],
                max_length=30,
            ),
        ),
    ]
