# Generated by Django 4.2.30 on 2026-09-24 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("disease", "0004_diseasescan_farmer_leaf_extent_and_more"),
        ("farms", "0006_farm_crop_variety_farm_soil_moisture_pct_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("extension", "Agricultural Extension Office"),
                            ("kvk", "Krishi Vigyan Kendra (KVK)"),
                            ("laboratory", "Phytopathology Diagnostic Laboratory"),
                        ],
                        default="kvk",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Reason for referral (e.g. uncertain diagnosis, critical risk)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recommended", "Recommended by System"),
                            ("requested", "Requested by Farmer"),
                            ("completed", "Completed by Expert/Officer"),
                            ("declined", "Declined / Inconclusive"),
                        ],
                        default="recommended",
                        max_length=20,
                    ),
                ),
                (
                    "directory_entry",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="KVK or extension center contact details from static directory",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Agronomist or extension staff resolution notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="farms.farm",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="disease.diseasescan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
