# Generated by Django 4.2.30 on 2026-09-23 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("disease", "0002_diseasescan_disease_name_diseasescan_plant_name"),
        ("expert", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_path", models.CharField(blank=True, max_length=500)),
                (
                    "original_prediction",
                    models.CharField(
                        help_text="Original ConvNeXt class", max_length=200
                    ),
                ),
                ("original_confidence", models.FloatField(default=0.0)),
                (
                    "ground_truth_label",
                    models.CharField(
                        help_text="Expert-verified ground truth class", max_length=200
                    ),
                ),
                (
                    "validation_source",
                    models.CharField(
                        choices=[
                            ("expert_verified", "Agronomist Expert Review"),
                            ("farmer_feedback", "Farmer Recheck Outcome"),
                            ("field_trial", "Agricultural Research Station Trial"),
                        ],
                        default="expert_verified",
                        max_length=30,
                    ),
                ),
                (
                    "dataset_split",
                    models.CharField(
                        choices=[
                            ("unassigned", "Unassigned"),
                            ("train", "Training Set (70%)"),
                            ("val", "Validation Set (15%)"),
                            ("test", "Test Set (15%)"),
                        ],
                        default="unassigned",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_records",
                        to="expert.expertreview",
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_records",
                        to="disease.diseasescan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
