# Generated by Django 4.2.30 on 2026-09-24 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackrecord",
            name="crop",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="feedbackrecord",
            name="image_sha256",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="feedbackrecord",
            name="is_demo",
            field=models.BooleanField(
                default=False, help_text="Excluded from training exports by default"
            ),
        ),
        migrations.AddField(
            model_name="feedbackrecord",
            name="region",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="feedbackrecord",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feedback_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feedbackrecord",
            name="dataset_split",
            field=models.CharField(
                choices=[
                    ("unassigned", "Unassigned"),
                    ("train", "Training Set (80%)"),
                    ("val", "Validation Set (10%)"),
                    ("test", "Test Set (10%)"),
                ],
                default="unassigned",
                max_length=20,
            ),
        ),
    ]
