# Generated by Django 4.2.30 on 2026-09-23 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("disease", "0002_diseasescan_disease_name_diseasescan_plant_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpertReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("confirmed", "Confirmed (AI Prediction Correct)"),
                            ("corrected", "Corrected (Agronomist Revised Diagnosis)"),
                            ("rejected", "Unusable / Inconclusive Image"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ai_predicted_class", models.CharField(blank=True, max_length=200)),
                ("ai_confidence", models.FloatField(default=0.0)),
                ("expert_crop", models.CharField(blank=True, max_length=100)),
                ("expert_disease", models.CharField(blank=True, max_length=100)),
                (
                    "expert_severity",
                    models.CharField(
                        choices=[
                            ("none", "None (Healthy)"),
                            ("low", "Low / Early Symptoms"),
                            ("medium", "Moderate Spread"),
                            ("high", "Severe / Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("is_healthy", models.BooleanField(default=False)),
                (
                    "confidence_rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Expert confidence score 1 (uncertain) to 5 (definitive diagnosis)",
                    ),
                ),
                (
                    "diagnosis_notes",
                    models.TextField(
                        blank=True,
                        help_text="Differential diagnostic notes explaining leaf lesions, fungal patterns, or physiological stress",
                    ),
                ),
                (
                    "action_plan",
                    models.TextField(
                        blank=True,
                        help_text="Certified field recommendations and remedial spray schedules",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expert_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_reviews",
                        to="disease.diseasescan",
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at"],
            },
        ),
    ]
