# Generated by Django 4.2.30 on 2026-09-11 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_name", models.CharField(max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("location_name", models.CharField(blank=True, max_length=200)),
                (
                    "crop",
                    models.CharField(
                        blank=True,
                        help_text="Primary crop grown on this farm",
                        max_length=100,
                    ),
                ),
                (
                    "soil_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("black", "Black Cotton Soil"),
                            ("red", "Red Soil"),
                            ("alluvial", "Alluvial Soil"),
                            ("sandy", "Sandy Soil"),
                            ("clayey", "Clayey Soil"),
                            ("loamy", "Loamy Soil"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "farm_size",
                    models.FloatField(blank=True, help_text="Size in acres", null=True),
                ),
                (
                    "irrigation_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("drip", "Drip Irrigation"),
                            ("sprinkler", "Sprinkler"),
                            ("flood", "Flood Irrigation"),
                            ("manual", "Manual"),
                            ("none", "No Irrigation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("emoji", models.CharField(blank=True, max_length=10)),
                ("planted_at", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("harvested", "Harvested"),
                            ("failed", "Failed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crops",
                        to="farms.farm",
                    ),
                ),
            ],
        ),
    ]
