# Generated by Django 4.2.30 on 2026-09-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0002_weathersnapshot_sustainabilityrecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crop",
            name="area_acres",
            field=models.FloatField(
                blank=True, help_text="Land area in acres", null=True
            ),
        ),
        migrations.AddField(
            model_name="crop",
            name="irrigation_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("drip", "Drip Irrigation"),
                    ("sprinkler", "Sprinkler Irrigation"),
                    ("flood", "Flood Irrigation"),
                    ("rainfed", "Rainfed"),
                    ("manual", "Manual"),
                    ("other", "Other"),
                ],
                help_text="Irrigation method used for this crop",
                max_length=50,
            ),
        ),
    ]
