# Generated by Django 4.2.30 on 2026-09-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0003_add_crop_area_irrigation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crop",
            name="area_acres",
        ),
        migrations.RemoveField(
            model_name="crop",
            name="irrigation_method",
        ),
    ]
