# Generated by Django 4.2.30 on 2026-09-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0004_remove_crop_area_acres_remove_crop_irrigation_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="crop_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("seedling", "Seedling"),
                    ("vegetative", "Vegetative"),
                    ("flowering", "Flowering"),
                    ("fruiting", "Fruiting"),
                    ("maturity", "Maturity / Ripening"),
                    ("harvest", "Harvest"),
                ],
                default="vegetative",
                help_text="Current growth stage of primary crop",
                max_length=30,
            ),
        ),
    ]
