# Generated by Django 4.2.30 on 2026-09-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0005_farm_crop_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="farm",
            name="crop_variety",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Specific crop variety name",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="soil_moisture_pct",
            field=models.FloatField(
                blank=True, help_text="Soil moisture percentage", null=True
            ),
        ),
        migrations.AddField(
            model_name="farm",
            name="soil_ph",
            field=models.FloatField(
                blank=True, help_text="Soil pH level (0-14)", null=True
            ),
        ),
    ]
