# Generated by Django 4.2.30 on 2026-09-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_farm_crop_variety_farm_soil_moisture_pct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farm_size',
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_area_acres',
            field=models.FloatField(blank=True, help_text='Calculated farm area in acres', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='farm_boundary',
            field=models.JSONField(blank=True, help_text='GeoJSON Polygon representing the actual farm boundary', null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='crop',
            field=models.CharField(help_text='Primary crop grown on this farm', max_length=100),
        ),
        migrations.AlterField(
            model_name='farm',
            name='crop_stage',
            field=models.CharField(choices=[('seedling', 'Seedling'), ('vegetative', 'Vegetative'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('maturity', 'Maturity / Ripening'), ('harvest', 'Harvest')], default='vegetative', help_text='Current growth stage of primary crop', max_length=30),
        ),
        migrations.AlterField(
            model_name='farm',
            name='irrigation_type',
            field=models.CharField(choices=[('drip', 'Drip Irrigation'), ('sprinkler', 'Sprinkler'), ('flood', 'Flood Irrigation'), ('manual', 'Manual'), ('none', 'No Irrigation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='farm',
            name='latitude',
            field=models.FloatField(help_text='Latitude of selected farm location'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='farm',
            name='longitude',
            field=models.FloatField(help_text='Longitude of selected farm location'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='soil_type',
            field=models.CharField(choices=[('black', 'Black Cotton Soil'), ('red', 'Red Soil'), ('alluvial', 'Alluvial Soil'), ('sandy', 'Sandy Soil'), ('clayey', 'Clayey Soil'), ('loamy', 'Loamy Soil')], max_length=50),
        ),
    ]
