# Generated by Django 4.2.30 on 2026-09-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0007_remove_farm_farm_size_farm_farm_area_acres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThermalObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='ECO_L2T_LSTE', help_text='NASA ECOSTRESS product identifier (e.g. ECO_L2T_LSTE)', max_length=100)),
                ('ecostress_product_id', models.CharField(blank=True, help_text='Granule UR / Producer Granule ID from NASA CMR', max_length=255)),
                ('observation_datetime', models.DateTimeField(help_text='Acquisition datetime of the ECOSTRESS observation')),
                ('mean_lst_c', models.FloatField(help_text='Mean Land Surface Temperature in °C')),
                ('median_lst_c', models.FloatField(help_text='Median Land Surface Temperature in °C')),
                ('min_lst_c', models.FloatField(help_text='Minimum Land Surface Temperature in °C')),
                ('max_lst_c', models.FloatField(help_text='Maximum Land Surface Temperature in °C')),
                ('lst_std_c', models.FloatField(help_text='Thermal variability / standard deviation in °C')),
                ('valid_pixel_count', models.IntegerField(help_text='Number of valid thermal pixels processed for the farm')),
                ('data_source', models.CharField(default='NASA ECOSTRESS', help_text='Official data provider', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermal_observations', to='farms.farm')),
            ],
            options={
                'ordering': ['-observation_datetime', '-created_at'],
            },
        ),
    ]
