# Generated by Django 4.2.30 on 2026-09-27 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_thermalobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='ECO_L3T_JET', help_text='NASA ECOSTRESS product identifier (e.g. ECO_L3T_JET)', max_length=100)),
                ('ecostress_product_id', models.CharField(blank=True, help_text='Granule UR / Producer Granule ID from NASA CMR', max_length=255)),
                ('observation_datetime', models.DateTimeField(help_text='Acquisition datetime of the ECOSTRESS ET observation')),
                ('mean_et', models.FloatField(help_text='Mean Evapotranspiration')),
                ('median_et', models.FloatField(help_text='Median Evapotranspiration')),
                ('min_et', models.FloatField(help_text='Minimum Evapotranspiration')),
                ('max_et', models.FloatField(help_text='Maximum Evapotranspiration')),
                ('et_std', models.FloatField(help_text='Evapotranspiration variability / standard deviation')),
                ('valid_pixel_count', models.IntegerField(help_text='Number of valid ET pixels processed for the farm')),
                ('unit', models.CharField(default='mm/day', help_text='Evapotranspiration unit (e.g. mm/day)', max_length=30)),
                ('data_source', models.CharField(default='NASA ECOSTRESS', help_text='Official data provider', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='et_observations', to='farms.farm')),
            ],
            options={
                'ordering': ['-observation_datetime', '-created_at'],
            },
        ),
    ]
