# Generated by Django 4.2.30 on 2026-09-27 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0009_etobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESIObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='ECO_L4T_ESI', help_text='NASA ECOSTRESS product identifier (e.g. ECO_L4T_ESI)', max_length=100)),
                ('ecostress_product_id', models.CharField(blank=True, help_text='Granule UR / Producer Granule ID from NASA CMR', max_length=255)),
                ('observation_datetime', models.DateTimeField(help_text='Acquisition datetime of the ECOSTRESS ESI observation')),
                ('mean_esi', models.FloatField(help_text='Mean Evaporative Stress Index (actual ET / PET)')),
                ('median_esi', models.FloatField(help_text='Median Evaporative Stress Index')),
                ('min_esi', models.FloatField(help_text='Minimum Evaporative Stress Index')),
                ('max_esi', models.FloatField(help_text='Maximum Evaporative Stress Index')),
                ('esi_std', models.FloatField(help_text='Evaporative Stress Index variability / standard deviation')),
                ('valid_pixel_count', models.IntegerField(help_text='Number of valid ESI pixels processed for the farm')),
                ('unit', models.CharField(default='ratio', help_text='ESI unit (dimensionless ratio ET/PET)', max_length=30)),
                ('data_source', models.CharField(default='NASA ECOSTRESS', help_text='Official data provider', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esi_observations', to='farms.farm')),
            ],
            options={
                'ordering': ['-observation_datetime', '-created_at'],
            },
        ),
    ]
