# Generated by Django 4.2.30 on 2026-09-27 17:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0010_esiobservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the environmental assessment was generated')),
                ('stress_level', models.CharField(choices=[('normal', 'Normal Environmental Condition'), ('mild', 'Mild Environmental Stress'), ('elevated', 'Elevated Environmental Stress'), ('high', 'High Environmental Stress')], default='normal', help_text='Deterministic rule-based environmental stress level', max_length=20)),
                ('summary', models.TextField(blank=True, default='', help_text='Plain-language summary of environmental conditions')),
                ('reasons', models.JSONField(default=list, help_text='Transparent list of triggered rule explanations based on actual data')),
                ('lst_status', models.JSONField(default=dict, help_text='LST metrics: latest, previous, baseline, delta, status')),
                ('et_status', models.JSONField(default=dict, help_text='ET metrics: latest, previous, baseline, delta, status')),
                ('esi_status', models.JSONField(default=dict, help_text='ESI metrics: latest, previous, baseline, delta, status')),
                ('weather_status', models.JSONField(default=dict, help_text='Weather metrics: temperature, humidity, precipitation, status')),
                ('data_sufficiency', models.JSONField(default=dict, help_text='Data sufficiency breakdown and baseline observation counts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-assessment_datetime', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_datetime', models.DateTimeField(help_text='Timestamp of the weather observation')),
                ('temperature', models.FloatField(help_text='Air temperature in °C')),
                ('relative_humidity', models.FloatField(help_text='Relative humidity in %')),
                ('apparent_temperature', models.FloatField(blank=True, help_text='Feels-like apparent temperature in °C', null=True)),
                ('precipitation', models.FloatField(default=0.0, help_text='Precipitation in mm')),
                ('wind_speed', models.FloatField(default=0.0, help_text='Wind speed in km/h')),
                ('wind_direction', models.FloatField(blank=True, help_text='Wind direction in degrees', null=True)),
                ('soil_moisture', models.FloatField(blank=True, help_text='Soil moisture 0-1cm in m³/m³', null=True)),
                ('vapour_pressure_deficit', models.FloatField(blank=True, help_text='Vapour Pressure Deficit in kPa', null=True)),
                ('et0_fao', models.FloatField(blank=True, help_text='Reference evapotranspiration ET0 in mm', null=True)),
                ('weather_code', models.IntegerField(blank=True, help_text='WMO weather condition code', null=True)),
                ('data_source', models.CharField(default='Open-Meteo', help_text='Weather data provider', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-observation_datetime', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='esiobservation',
            index=models.Index(fields=['farm', '-observation_datetime'], name='farms_esiob_farm_id_acc9ba_idx'),
        ),
        migrations.AddIndex(
            model_name='esiobservation',
            index=models.Index(fields=['farm', 'ecostress_product_id'], name='farms_esiob_farm_id_4e2d92_idx'),
        ),
        migrations.AddIndex(
            model_name='esiobservation',
            index=models.Index(fields=['farm', 'created_at'], name='farms_esiob_farm_id_88935a_idx'),
        ),
        migrations.AddIndex(
            model_name='etobservation',
            index=models.Index(fields=['farm', '-observation_datetime'], name='farms_etobs_farm_id_99ea3a_idx'),
        ),
        migrations.AddIndex(
            model_name='etobservation',
            index=models.Index(fields=['farm', 'ecostress_product_id'], name='farms_etobs_farm_id_6f6c68_idx'),
        ),
        migrations.AddIndex(
            model_name='etobservation',
            index=models.Index(fields=['farm', 'created_at'], name='farms_etobs_farm_id_4d5286_idx'),
        ),
        migrations.AddIndex(
            model_name='thermalobservation',
            index=models.Index(fields=['farm', '-observation_datetime'], name='farms_therm_farm_id_15dd73_idx'),
        ),
        migrations.AddIndex(
            model_name='thermalobservation',
            index=models.Index(fields=['farm', 'ecostress_product_id'], name='farms_therm_farm_id_d35d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='thermalobservation',
            index=models.Index(fields=['farm', 'created_at'], name='farms_therm_farm_id_ac006b_idx'),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_observations', to='farms.farm'),
        ),
        migrations.AddField(
            model_name='environmentalriskassessment',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environmental_risk_assessments', to='farms.farm'),
        ),
        migrations.AddIndex(
            model_name='weatherobservation',
            index=models.Index(fields=['farm', '-observation_datetime'], name='farms_weath_farm_id_f927f1_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherobservation',
            index=models.Index(fields=['farm', 'created_at'], name='farms_weath_farm_id_2e32bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='weatherobservation',
            constraint=models.UniqueConstraint(fields=('farm', 'observation_datetime', 'data_source'), name='unique_farm_weather_obs'),
        ),
        migrations.AddIndex(
            model_name='environmentalriskassessment',
            index=models.Index(fields=['farm', '-assessment_datetime'], name='farms_envir_farm_id_e99023_idx'),
        ),
        migrations.AddIndex(
            model_name='environmentalriskassessment',
            index=models.Index(fields=['farm', 'stress_level'], name='farms_envir_farm_id_4fad78_idx'),
        ),
    ]
