# Generated by Django 4.2.30 on 2026-09-23 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0005_farm_crop_stage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PestObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trap_type",
                    models.CharField(
                        choices=[
                            ("sticky_yellow", "Yellow Sticky Trap"),
                            ("sticky_blue", "Blue Sticky Trap"),
                            ("pheromone", "Pheromone Trap"),
                            ("light", "Light Trap"),
                            ("pitfall", "Pitfall Trap"),
                            ("manual", "Manual Canopy Scouting"),
                        ],
                        default="sticky_yellow",
                        max_length=30,
                    ),
                ),
                (
                    "pest_type",
                    models.CharField(
                        choices=[
                            ("Whitefly", "Whitefly (Bemisia tabaci)"),
                            ("Aphid", "Aphid (Aphis gossypii)"),
                            ("Thrips", "Thrips (Thrips tabaci)"),
                            ("Spider Mite", "Spider Mite (Tetranychidae)"),
                            ("Fruit Fly", "Fruit Fly (Bactrocera)"),
                            ("Bollworm", "Bollworm / Pod Borer (Helicoverpa armigera)"),
                            ("Other", "Other Pest Species"),
                        ],
                        default="Whitefly",
                        max_length=50,
                    ),
                ),
                (
                    "pest_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Observed count of pests per trap or leaflet",
                    ),
                ),
                (
                    "threshold_level",
                    models.CharField(
                        choices=[
                            ("normal", "Normal / Below Threshold"),
                            ("alert", "Scouting Alert / Increasing"),
                            (
                                "action_required",
                                "Action Required / Economic Injury Level Exceeded",
                            ),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="pest_traps/"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Farmer or scout observations on field trap location and weather",
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pest_observations",
                        to="farms.farm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pest_observations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_at"],
            },
        ),
    ]
