# Generated by Django 4.2.30 on 2026-09-14 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0004_remove_crop_area_acres_remove_crop_irrigation_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CropPredictionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nitrogen", models.FloatField(help_text="N in kg/ha")),
                ("phosphorus", models.FloatField(help_text="P in kg/ha")),
                ("potassium", models.FloatField(help_text="K in kg/ha")),
                ("ph", models.FloatField(help_text="Soil pH value")),
                ("temperature", models.FloatField(help_text="Temperature in °C")),
                ("humidity", models.FloatField(help_text="Relative humidity in %")),
                ("rainfall", models.FloatField(help_text="Rainfall in mm")),
                ("recommended_crop", models.CharField(max_length=100)),
                (
                    "confidence",
                    models.FloatField(help_text="Top-1 probability 0.0 - 1.0"),
                ),
                ("top_3_crops", models.JSONField(blank=True, default=list)),
                ("agronomic_details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_predictions",
                        to="farms.farm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
