# Generated by Django 4.2.30 on 2026-09-23 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0005_farm_crop_stage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("disease", "0002_diseasescan_disease_name_diseasescan_plant_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateField(
                        help_text="Recommended follow-up verification date (typically 5-7 days after treatment)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Evaluation"),
                            (
                                "resolved",
                                "Completely Resolved (Healthy Tissue Regenerated)",
                            ),
                            ("improved", "Improved (Lesion Spread Halted)"),
                            ("unchanged", "Unchanged / Stagnant"),
                            ("worsened", "Worsened / Spread to Surrounding Foliage"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "intervention_applied",
                    models.TextField(
                        blank=True,
                        help_text="Description of cultural, biological, or chemical interventions executed by farmer",
                    ),
                ),
                (
                    "recovery_percentage",
                    models.FloatField(
                        blank=True,
                        help_text="Estimated crop canopy recovery percentage (0 to 100)",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="farms.farm",
                    ),
                ),
                (
                    "original_scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="disease.diseasescan",
                    ),
                ),
                (
                    "recheck_scan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="is_followup_for",
                        to="disease.diseasescan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_ups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date", "-created_at"],
            },
        ),
    ]
