# Generated by Django 4.2.30 on 2026-09-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0006_farm_crop_variety_farm_soil_moisture_pct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "soil_moisture",
                    models.FloatField(
                        blank=True, help_text="Soil moisture percentage", null=True
                    ),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True, help_text="Air/Soil temperature in °C", null=True
                    ),
                ),
                (
                    "humidity",
                    models.FloatField(
                        blank=True, help_text="Relative humidity %", null=True
                    ),
                ),
                (
                    "ph",
                    models.FloatField(
                        blank=True, help_text="Soil pH (0-14)", null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Entry"),
                            ("simulated", "Simulated Stream Feed"),
                            ("device_api", "Device API"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_readings",
                        to="farms.farm",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
    ]
